name: Pridebot
version: '1.0.0'
main: dev.sdriver1.pridebot.Pridebot
api-version: '1.21'

commands:
  gaydar:
    description: How gay are you (or another player)?
    usage: /gaydar [player]
  transdar:
    description: How trans are you (or another player)?
    usage: /transdar [player]
  gender:
    description: Show info & flag for a given gender identity
    usage: /gender <gender>
    permission: pridebot.gender
  sexuality:
    description: Show info & flag for a given sexuality
    usage: /sexuality <sexuality>
    permission: pridebot.sexuality
  list:
    description: List supported genders or sexualities (or all)
    usage: /list <genders|sexualities|all>

permissions:
  pridebot.gaydar:
    description: Allows using /gaydar
    default: true
  pridebot.transdar:
    description: Allows using /transdar
    default: true
  pridebot.gender:
    description: Allows using /gender
    default: true
  pridebot.sexuality:
    description: Allows using /sexuality
    default: true
  pridebot.list:
    description: Allows using /list
    default: true